//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIhsan.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Styles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Styles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyIhsan.LanguageResources.Styles", typeof(Styles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animate.css.
        /// </summary>
        public static string animate {
            get {
                return ResourceManager.GetString("animate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bootstrap.min.rtl.css.
        /// </summary>
        public static string bootstrap {
            get {
                return ResourceManager.GetString("bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bootstrapDatepiker1.8.0.css.
        /// </summary>
        public static string bootstrapDatepiker {
            get {
                return ResourceManager.GetString("bootstrapDatepiker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bootstrap-toggle.min.css.
        /// </summary>
        public static string bootstraptoggle {
            get {
                return ResourceManager.GetString("bootstraptoggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to components-rtl.min.css.
        /// </summary>
        public static string component {
            get {
                return ResourceManager.GetString("component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darkblue-rtl.min.css.
        /// </summary>
        public static string darkblue {
            get {
                return ResourceManager.GetString("darkblue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datatables.min.css.
        /// </summary>
        public static string datatable {
            get {
                return ResourceManager.GetString("datatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixes.css.
        /// </summary>
        public static string fixes {
            get {
                return ResourceManager.GetString("fixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layout-rtl.min.css.
        /// </summary>
        public static string layout {
            get {
                return ResourceManager.GetString("layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.css.
        /// </summary>
        public static string loginStyle {
            get {
                return ResourceManager.GetString("loginStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pace-theme-minimal.css.
        /// </summary>
        public static string pace {
            get {
                return ResourceManager.GetString("pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to perfect-scrollbar.css.
        /// </summary>
        public static string perfectscrollbar {
            get {
                return ResourceManager.GetString("perfectscrollbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.js.
        /// </summary>
        public static string scriptscustom {
            get {
                return ResourceManager.GetString("scriptscustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select2.min.css.
        /// </summary>
        public static string select2 {
            get {
                return ResourceManager.GetString("select2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slick.css.
        /// </summary>
        public static string slick {
            get {
                return ResourceManager.GetString("slick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slick-theme.css.
        /// </summary>
        public static string slickThem {
            get {
                return ResourceManager.GetString("slickThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toastr.css.
        /// </summary>
        public static string toastr {
            get {
                return ResourceManager.GetString("toastr", resourceCulture);
            }
        }
    }
}
