//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIhsan.LanguageResources.Authentication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Auth {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Auth() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyIhsan.LanguageResources.Authentication.Auth", typeof(Auth).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة اقسام.
        /// </summary>
        public static string addDepartment {
            get {
                return ResourceManager.GetString("addDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة جمعية.
        /// </summary>
        public static string addEntity {
            get {
                return ResourceManager.GetString("addEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة جديد.
        /// </summary>
        public static string addNew {
            get {
                return ResourceManager.GetString("addNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة مستخدمين.
        /// </summary>
        public static string addUsers {
            get {
                return ResourceManager.GetString("addUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء الاختيار.
        /// </summary>
        public static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاكيد كلمة المرور.
        /// </summary>
        public static string confirmPass {
            get {
                return ResourceManager.GetString("confirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم السري غير متطابق.
        /// </summary>
        public static string confirmPassRegx {
            get {
                return ResourceManager.GetString("confirmPassRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الدولة.
        /// </summary>
        public static string countryRegx {
            get {
                return ResourceManager.GetString("countryRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة اقسام.
        /// </summary>
        public static string departmentPopupTitle {
            get {
                return ResourceManager.GetString("departmentPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاقسام.
        /// </summary>
        public static string departments {
            get {
                return ResourceManager.GetString("departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صيغة البريد غير صحيحة.
        /// </summary>
        public static string emailRegx {
            get {
                return ResourceManager.GetString("emailRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل البريد الالكتروني.
        /// </summary>
        public static string emailVal {
            get {
                return ResourceManager.GetString("emailVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل جهة العمل.
        /// </summary>
        public static string employeerRegx {
            get {
                return ResourceManager.GetString("employeerRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة العمل.
        /// </summary>
        public static string employer {
            get {
                return ResourceManager.GetString("employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت النهايه.
        /// </summary>
        public static string endTime {
            get {
                return ResourceManager.GetString("endTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة جمعيات.
        /// </summary>
        public static string entitiesPopupTitle {
            get {
                return ResourceManager.GetString("entitiesPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمعية.
        /// </summary>
        public static string entity {
            get {
                return ResourceManager.GetString("entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل النوع.
        /// </summary>
        public static string genderRegx {
            get {
                return ResourceManager.GetString("genderRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم.
        /// </summary>
        public static string gridUsername {
            get {
                return ResourceManager.GetString("gridUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني موجود من قبل.
        /// </summary>
        public static string mailExist {
            get {
                return ResourceManager.GetString("mailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموبايل.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموبيل موجود من قبل.
        /// </summary>
        public static string mobileExist {
            get {
                return ResourceManager.GetString("mobileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاســم.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم لاتيني.
        /// </summary>
        public static string nameEn {
            get {
                return ResourceManager.GetString("nameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الاسم لاتيني.
        /// </summary>
        public static string nameEnRegx {
            get {
                return ResourceManager.GetString("nameEnRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الاسم.
        /// </summary>
        public static string nameRegx {
            get {
                return ResourceManager.GetString("nameRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string nameTranslate {
            get {
                return ResourceManager.GetString("nameTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشاشات الرئيسية.
        /// </summary>
        public static string page1 {
            get {
                return ResourceManager.GetString("page1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشاشات الغير مختارة.
        /// </summary>
        public static string page2 {
            get {
                return ResourceManager.GetString("page2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشاشات الفرعية.
        /// </summary>
        public static string page3 {
            get {
                return ResourceManager.GetString("page3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشاشات المختارة.
        /// </summary>
        public static string page4 {
            get {
                return ResourceManager.GetString("page4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر كلمة مرور اكبر من 5 واقل من 20 رقم .
        /// </summary>
        public static string passRegx {
            get {
                return ResourceManager.GetString("passRegx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل كلمة المرور.
        /// </summary>
        public static string passVal {
            get {
                return ResourceManager.GetString("passVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المده.
        /// </summary>
        public static string period {
            get {
                return ResourceManager.GetString("period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ العمليه.
        /// </summary>
        public static string pullOutDate {
            get {
                return ResourceManager.GetString("pullOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض عمليات سحب البيانات.
        /// </summary>
        public static string pullOutTitle {
            get {
                return ResourceManager.GetString("pullOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدور الوظيفي.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدور الوظيفي موجود بالفعل.
        /// </summary>
        public static string roleExist {
            get {
                return ResourceManager.GetString("roleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث الدور الوظيفي.
        /// </summary>
        public static string roleSearch {
            get {
                return ResourceManager.GetString("roleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الشاشة.
        /// </summary>
        public static string screenName {
            get {
                return ResourceManager.GetString("screenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screenNameAr.
        /// </summary>
        public static string screenNameCol {
            get {
                return ResourceManager.GetString("screenNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلاحيات الشاشات.
        /// </summary>
        public static string screens {
            get {
                return ResourceManager.GetString("screens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت البدايه.
        /// </summary>
        public static string startTime {
            get {
                return ResourceManager.GetString("startTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحاله.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف موجود من قبل.
        /// </summary>
        public static string telExist {
            get {
                return ResourceManager.GetString("telExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المسخدم موجود من قبل.
        /// </summary>
        public static string usernameExist {
            get {
                return ResourceManager.GetString("usernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل اسم المستخدم.
        /// </summary>
        public static string usernameVal {
            get {
                return ResourceManager.GetString("usernameVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث المستخدمين.
        /// </summary>
        public static string userSearchCaption {
            get {
                return ResourceManager.GetString("userSearchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد المستخدمين.
        /// </summary>
        public static string usersNo {
            get {
                return ResourceManager.GetString("usersNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        public static string usersPopupTitle {
            get {
                return ResourceManager.GetString("usersPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدمين.
        /// </summary>
        public static string userTitleCaption {
            get {
                return ResourceManager.GetString("userTitleCaption", resourceCulture);
            }
        }
    }
}
